### ISSUE TITLE
This is a stolen version of mq-scss

### ISSUE THREAD

**Issue by Dan503** [zanjs/media-scss#1]
This is in violation of the MIT Licence.

This is an exact replica of my mq-scss mixin:
https://github.com/Dan503/mq-scss

If you find this mixin useful. Use the official one.

**Comment by zanjs** [comment]
@Dan503  ok thinks

**Comment by Dan503** [comment]
I'm going to ask you to delete this repository and unpublish the package from npm or I will submit a DMCA takedown notice

https://github.com/contact/dmca
